name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
      runs-on: ubuntu-latest
      steps:
        # uses GitHub's checkout action to checkout code from the master branch
        - name: Checkout
          uses: actions/checkout@v2.3.1
        # sets up .NET SDK
        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v1.2.3
          with:
            dotnet-version: 6.0
        # publishes Blazor project to the release-folder
        - name: Publich .NET Project
          run: dotnet publish Physics.csproj -c Release -o release --nologo
        - name: Commit wwwroot to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@4.1.7
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: release/wwwroot
          
